using Xunit;

namespace Employee_Management_System.EntityFrameworkCore;

[CollectionDefinition(Employee_Management_SystemTestConsts.CollectionDefinitionName)]
public class Employee_Management_SystemEntityFrameworkCoreCollection : ICollectionFixture<Employee_Management_SystemEntityFrameworkCoreFixture>
{

}
