using Employee_Management_System.EntityFrameworkCore;
using Xunit;

namespace Employee_Management_System.EntityFrameworkCore;

public class Employee_Management_SystemEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<Employee_Management_SystemEntityFrameworkCoreFixture>
{

}
